# Algospot ansible settings
# vim: set et ts=2 sts=2 sw=2

- name: "update apt repository cache"
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: "install apt packages"
  apt: name={{item}} state=present
  sudo: yes
  with_items:
  - python-setuptools
  - python-dev
  - build-essential
  - git-core
  - libjpeg-dev
  - postgresql-9.3
  - postgresql-contrib-9.3
  - postgresql-server-dev-9.3
  - libffi-dev
  - rabbitmq-server

- name: "install pip"
  sudo: yes
  easy_install: name=pip

- name: "install python dependencies"
  sudo: yes
  pip: name={{item}}
  with_items:
  - Django==1.7
  - uwsgi
  - Pillow
  - psycopg2
  - pytz
  - django-celery-email
  - celery
  - django-extensions
  - django-taggit
  - django-jsonfield
  - markdown
  - bcrypt
  - pygments

- name: "add nginx stable"
  sudo: yes
  apt_repository: repo='ppa:nginx/stable'

- name: "install nginx"
  sudo: yes
  apt: name=nginx

- name: "create postgres user"
  postgresql_user: name={{user}} role_attr_flags=SUPERUSER
  sudo_user: postgres
  sudo: yes

- name: "create postgres user root"
  postgresql_user: name=root role_attr_flags=SUPERUSER
  sudo_user: postgres
  sudo: yes

- name: "create jmk database"
  postgresql_db: name={{db_name}}
  sudo: yes
  sudo_user: postgres

